import 'package:flutter/cupertino.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import '../models/platform_model.dart';

class AppPlatforms {
  static const List<PlatformModel> availablePlatforms = [
    PlatformModel(
      id: 'instagram',
      name: 'Instagram',
      icon: FontAwesomeIcons.instagram,
      color: Color(0xFFE1306C),
      inputHint: 'Instagram profil linki veya kullanıcı adı...',
    ),
    PlatformModel(
      id: 'x-twitter',
      name: 'X (Twitter)',
      icon: FontAwesomeIcons.xTwitter,
      color: Color(0xFF000000),
      inputHint: 'X (Twitter) kullanıcı adı veya linki...',
    ),
    PlatformModel(
      id: 'facebook',
      name: 'Facebook',
      icon: FontAwesomeIcons.facebookF,
      color: Color(0xFF1877F2),
      inputHint: 'Facebook profil linki...',
    ),
    PlatformModel(
      id: 'snapchat',
      name: 'Snapchat',
      icon: FontAwesomeIcons.snapchat,
      color: Color(0xFFFFFC00),
      inputHint: 'Snapchat kullanıcı adı...',
    ),
    PlatformModel(
      id: 'tiktok',
      name: 'TikTok',
      icon: FontAwesomeIcons.tiktok,
      color: Color(0xFF000000),
      inputHint: 'TikTok kullanıcı adı veya link...',
    ),
    PlatformModel(
      id: 'linkedin',
      name: 'LinkedIn',
      icon: FontAwesomeIcons.linkedinIn,
      color: Color(0xFF0A66C2),
      inputHint: 'LinkedIn profil linki...',
    ),
    PlatformModel(
      id: 'youtube',
      name: 'YouTube',
      icon: FontAwesomeIcons.youtube,
      color: Color(0xFFFF0000),
      inputHint: 'YouTube kanal linki...',
    ),
    PlatformModel(
      id: 'whatsapp',
      name: 'WhatsApp',
      icon: FontAwesomeIcons.whatsapp,
      color: Color(0xFF25D366),
      inputHint: 'WhatsApp telefon numarası...',
    ),
    PlatformModel(
      id: 'telegram',
      name: 'Telegram',
      icon: FontAwesomeIcons.telegram,
      color: Color(0xFF229ED9),
      inputHint: 'Telegram kullanıcı adı...',
    ),
    PlatformModel(
      id: 'spotify',
      name: 'Spotify',
      icon: FontAwesomeIcons.spotify,
      color: Color(0xFF1DB954),
      inputHint: 'Spotify playlist veya hesap linki...',
    ),
    PlatformModel(
      id: 'discord',
      name: 'Discord',
      icon: FontAwesomeIcons.discord,
      color: Color(0xFF5865F2),
      inputHint: 'Discord sunucu davet linki...',
    ),
    PlatformModel(
      id: 'reddit',
      name: 'Reddit',
      icon: FontAwesomeIcons.reddit,
      color: Color(0xFFFF4500),
      inputHint: 'Reddit kullanıcı adı veya link...',
    ),
    PlatformModel(
      id: 'github',
      name: 'Github',
      icon: FontAwesomeIcons.github,
      color: Color(0xFF94A3B8),
      inputHint: 'GitHub profil linki...',
    ),
    PlatformModel(
      id: 'pinterest',
      name: 'Pinterest',
      icon: FontAwesomeIcons.pinterest,
      color: Color(0xFFE60023),
      inputHint: 'Pinterest profil linki...',
    ),
    PlatformModel(
      id: 'twitch',
      name: 'Twitch',
      icon: FontAwesomeIcons.twitch,
      color: Color(0xFF9146FF),
      inputHint: 'Twitch kanal linki...',
    ),
    PlatformModel(
      id: 'threads',
      name: 'Threads',
      icon: FontAwesomeIcons.threads,
      color: Color(0xFF000000),
      inputHint: 'Threads profil linki...',
    ),
    PlatformModel(
      id: 'appstore',
      name: 'App Store',
      icon: FontAwesomeIcons.appStoreIos,
      color: Color(0xFF007AFF),
      inputHint: 'App Store linki...',
    ),
    PlatformModel(
      id: 'googleplay',
      name: 'Google Play',
      icon: FontAwesomeIcons.googlePlay,
      color: Color(0xFF34A853),
      inputHint: 'Play Store linki...',
    ),
    PlatformModel(
      id: 'website',
      name: 'Website',
      icon: FontAwesomeIcons.globe,
      color: Color(0xFF00D2FF),
      inputHint: 'URL web sitesi linki...',
    ),
    PlatformModel(
      id: 'email',
      name: 'E-posta',
      icon: CupertinoIcons.mail,
      color: Color(0xFFEA4335),
      inputHint: 'E-posta adresini girin...',
    ),
    PlatformModel(
      id: 'slack',
      name: 'Slack',
      icon: FontAwesomeIcons.slack,
      color: Color(0xFF4A154B),
      inputHint: 'Slack kanal linki...',
    ),
    PlatformModel(
      id: 'wifi',
      name: 'WiFi',
      icon: CupertinoIcons.wifi,
      color: Color(0xFF007AFF),
      inputHint: 'WiFi bilgilerini girin...',
    ),
    PlatformModel(
      id: 'phone',
      name: 'Telefon',
      icon: CupertinoIcons.phone,
      color: Color(0xFF34C759),
      inputHint: 'Telefon numarasını girin...',
    ),
    PlatformModel(
      id: 'other',
      name: 'Diğer',
      icon: CupertinoIcons.link,
      color: Color(0xFF8E8E93),
      inputHint: 'Herhangi bir link...',
    ),
  ];
}
