// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiKb0N6aYoB9fMguhlBZmtnhun98bJ6iI',
    appId: '1:1085894990290:web:42f9fd43ece4426fd9900b',
    messagingSenderId: '1085894990290',
    projectId: 'quiro-5c21e',
    authDomain: 'quiro-5c21e.firebaseapp.com',
    storageBucket: 'quiro-5c21e.firebasestorage.app',
    measurementId: 'G-F0K2HRSHFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt1b-TLUqkY3q2QaTnfvq5B6OKBN_2v6I',
    appId: '1:1085894990290:android:09511a7b6ee43538d9900b',
    messagingSenderId: '1085894990290',
    projectId: 'quiro-5c21e',
    storageBucket: 'quiro-5c21e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXC8_XJYQRmo4cEOGjDMYLZqF409-JAZQ',
    appId: '1:1085894990290:ios:786ef1c7b5f88f5ad9900b',
    messagingSenderId: '1085894990290',
    projectId: 'quiro-5c21e',
    storageBucket: 'quiro-5c21e.firebasestorage.app',
    iosClientId:
        '1085894990290-6j78rmn9lnqu43sikghetfoe869gtit5.apps.googleusercontent.com',
    iosBundleId: 'com.mgverse.Qurio',
  );
}
